"""Initial migration: create regions and stats tables

Revision ID: e0532d9f72a9
Revises: 
Create Date: 2025-05-14 15:21:02.412533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0532d9f72a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('item_date_published', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('num_newspaper', sa.Integer(), nullable=True),
    sa.Column('num_feeds', sa.Integer(), nullable=True),
    sa.Column('av_sents', sa.Float(), nullable=True),
    sa.Column('num_news', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('global_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_stats_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_stats_item_date_published'), ['item_date_published'], unique=False)

    op.create_table('regions',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('region_id')
    )
    op.create_table('regional_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('item_date_published', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('num_words', sa.Float(), nullable=True),
    sa.Column('rauh_sents_share', sa.Float(), nullable=True),
    sa.Column('rauh_sents_av', sa.Float(), nullable=True),
    sa.Column('happiness_share', sa.Float(), nullable=True),
    sa.Column('happiness_av', sa.Float(), nullable=True),
    sa.Column('val_share', sa.Float(), nullable=True),
    sa.Column('val_av', sa.Float(), nullable=True),
    sa.Column('num_papers', sa.Integer(), nullable=True),
    sa.Column('num_news', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regional_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regional_data_item_date_published'), ['item_date_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_regional_data_region_id'), ['region_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regional_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regional_data_region_id'))
        batch_op.drop_index(batch_op.f('ix_regional_data_item_date_published'))

    op.drop_table('regional_data')
    op.drop_table('regions')
    with op.batch_alter_table('global_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_stats_item_date_published'))
        batch_op.drop_index(batch_op.f('ix_global_stats_country'))

    op.drop_table('global_stats')
    # ### end Alembic commands ###
